language: scala
sbt_args: -J-Dproject.version=travis-SNAPSHOT
scala:
  - 2.10.5
  - 2.11.7
  - 2.12.0-M1
  - 2.12.0-M2
jdk:
  # - oraclejdk7
  - oraclejdk8
  # - openjdk7
# sudo: false
cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt